# Generated by Django 6.0.6 on 2026-06-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_deal_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="recipients",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="to",
        ),
    ]
