# Generated by Django 6.0.6 on 2026-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_siteconfig_finder_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("connect", "Connect"),
                    ("check_pending", "Check Pending"),
                    ("follow_up", "Follow Up"),
                    ("email", "Email"),
                ],
                max_length=20,
            ),
        ),
    ]
