# Generated by Django 6.0.6 on 2026-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="contacts_api_token",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="contacts_api_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
