from __future__ import annotations

import os
import sys
from pathlib import Path


def _bootstrap_repo_root() -> Path:
    repo_root = Path(__file__).resolve().parents[1]
    repo_root_str = str(repo_root)
    if repo_root_str not in sys.path:
        sys.path.insert(0, repo_root_str)
    return repo_root


_bootstrap_repo_root()

from linkedin_cli import content


def _dedupe_terms(terms: list[str]) -> list[str]:
    return list(dict.fromkeys(term.strip() for term in terms if term and term.strip()))


TECH_INDUSTRY_HINTS = {
    "ai",
    "artificial intelligence",
    "agentic ai",
    "machine learning",
    "deep learning",
    "computer vision",
    "voice ai",
    "synthetic data",
    "cybersecurity",
    "cloud",
    "data",
    "analytics",
    "business intelligence",
    "devtools",
    "infrastructure",
    "software",
    "enterprise software",
    "application security",
    "identity",
    "observability",
    "database",
    "data infrastructure",
    "integration platform",
    "api platform",
    "developer platform",
    "saas",
    "open source",
    "mlops",
    "finops",
    "devsecops",
    "platform ops",
    "robotics",
    "industrial automation",
    "semiconductors",
    "electronics",
    "iot",
    "digital twins",
    "search",
    "automation software",
    "workflow software",
    "document ai",
    "enterprise search",
    "call center software",
}

GTM_INDUSTRY_HINTS = {
    "sales",
    "marketing",
    "martech",
    "adtech",
    "revops",
    "customer success",
    "customer support",
    "field marketing",
    "demand generation",
    "growth marketing",
    "brand marketing",
    "content marketing",
    "partner marketing",
    "sales ops",
    "pre sales",
    "recruiting",
    "staffing",
    "hrtech",
    "people ops",
    "talent acquisition",
}

TECH_TOPIC_HINTS = {
    "agents",
    "agent orchestration",
    "multi agent systems",
    "automation",
    "workflow",
    "copilots",
    "genai",
    "llm",
    "rag",
    "evals",
    "fine tuning",
    "prompting",
    "tool use",
    "orchestration",
    "observability",
    "security",
    "application security",
    "cloud security",
    "data security",
    "identity security",
    "compliance",
    "governance",
    "analytics",
    "data engineering",
    "data quality",
    "data governance",
    "data catalog",
    "etl",
    "elt",
    "vector database",
    "data warehouse",
    "lakehouse",
    "platform engineering",
    "developer experience",
    "devops",
    "mlops",
    "aiops",
    "reliability",
    "sre",
    "incident response",
    "postmortem",
    "on call",
    "cloud costs",
    "finops",
    "zero trust",
    "identity",
    "fraud",
    "api design",
    "sdk",
    "workflow automation",
    "process mining",
    "document processing",
    "knowledge base",
    "search",
    "enterprise search",
    "chatbots",
    "voice agents",
    "contact center",
    "support automation",
    "model context protocol",
    "mcp",
    "browser automation",
    "computer use",
    "agent memory",
    "knowledge graphs",
    "graph rag",
    "synthetic evals",
    "grounded generation",
    "human in the loop",
    "approval workflows",
    "audit trails",
    "SOC 2",
    "HIPAA",
    "PCI",
    "GDPR",
    "KYC",
    "AML",
    "identity verification",
    "search relevance",
    "recommendation systems",
}

GTM_TOPIC_HINTS = {
    "growth",
    "strategy",
    "operations",
    "execution",
    "scaling",
    "product",
    "roadmap",
    "user research",
    "onboarding",
    "activation",
    "retention",
    "churn",
    "personalization",
    "experimentation",
    "ab testing",
    "pricing",
    "packaging",
    "monetization",
    "upsell",
    "cross sell",
    "plg",
    "product led growth",
    "product marketing",
    "positioning",
    "messaging",
    "brand",
    "storytelling",
    "community",
    "distribution",
    "partnerships",
    "ecosystem",
    "channel sales",
    "alliances",
    "sales",
    "pipeline",
    "forecasting",
    "enablement",
    "outbound",
    "inbound",
    "lead gen",
    "demand gen",
    "account based marketing",
    "abm",
    "revops",
    "customer success",
    "customer support",
    "renewals",
    "expansion revenue",
    "hiring",
    "recruiting",
    "talent",
    "management",
    "leadership",
    "founder mode",
    "case study",
    "benchmark",
    "playbook",
    "lessons",
    "templates",
    "mistakes",
    "launch",
    "demo",
    "gtm",
    "roi",
    "best practices",
    "competitive intelligence",
    "battlecards",
    "customer stories",
    "thought leadership",
    "qbr",
    "pipeline review",
    "career growth",
    "manager training",
    "change management",
    "digital transformation",
    "crm hygiene",
    "conversion",
    "click through rate",
    "attribution",
    "measurement",
    "dashboards",
    "budgeting",
    "planning",
    "scenario planning",
    "board reporting",
    "fundraising",
    "series a",
    "seed",
    "partnership strategy",
}


def _query_domain(term: str, industry_terms: set[str], topic_terms: set[str]) -> str:
    if term in industry_terms:
        if term in GTM_INDUSTRY_HINTS:
            return "gtm"
        if term in TECH_INDUSTRY_HINTS:
            return "tech"
        return "general"
    if term in topic_terms:
        if term in GTM_TOPIC_HINTS:
            return "gtm"
        if term in TECH_TOPIC_HINTS:
            return "tech"
        return "general"
    return "general"


def _filter_queries(queries: list[str]) -> list[str]:
    industry_terms = set(INDUSTRIES)
    topic_terms = set(TOPICS)
    filtered: list[str] = []
    for query in queries:
        text = query.replace("site:linkedin.com/posts ", "").replace("site:linkedin.com/feed/update ", "").strip()
        lowered = text.lower()
        matched_industry = next((term for term in sorted(industry_terms, key=len, reverse=True) if lowered.startswith(term)), None)
        if not matched_industry:
            filtered.append(query)
            continue
        remainder = lowered[len(matched_industry) :].strip().strip('"')
        matched_topic = next((term for term in sorted(topic_terms, key=len, reverse=True) if remainder.startswith(term)), None)
        if not matched_topic:
            filtered.append(query)
            continue
        industry_domain = _query_domain(matched_industry, industry_terms, topic_terms)
        topic_domain = _query_domain(matched_topic, industry_terms, topic_terms)
        if "site:linkedin.com/posts" in query and industry_domain == "tech" and topic_domain == "gtm":
            continue
        filtered.append(query)
    return filtered


INDUSTRIES = _dedupe_terms(
    [
        "ai",
        "artificial intelligence",
        "agentic ai",
        "machine learning",
        "deep learning",
        "computer vision",
        "voice ai",
        "synthetic data",
        "cybersecurity",
        "cloud",
        "data",
        "analytics",
        "business intelligence",
        "devtools",
        "infrastructure",
        "software",
        "enterprise software",
        "application security",
        "identity",
        "observability",
        "database",
        "data infrastructure",
        "integration platform",
        "api platform",
        "developer platform",
        "saas",
        "open source",
        "mlops",
        "finops",
        "devsecops",
        "platform ops",
        "fintech",
        "banking",
        "payments",
        "insurtech",
        "wealthtech",
        "lending",
        "personal finance",
        "accounting software",
        "treasury",
        "tax technology",
        "capital markets",
        "asset management",
        "crypto",
        "blockchain",
        "web3",
        "defi",
        "healthcare",
        "biotech",
        "pharma",
        "medtech",
        "life sciences",
        "digital health",
        "clinical operations",
        "payer",
        "provider",
        "hospital systems",
        "medical devices",
        "revenue cycle",
        "health IT",
        "telehealth",
        "mental health",
        "sales",
        "marketing",
        "martech",
        "adtech",
        "revops",
        "customer success",
        "customer support",
        "field marketing",
        "demand generation",
        "growth marketing",
        "brand marketing",
        "content marketing",
        "partner marketing",
        "sales ops",
        "pre sales",
        "recruiting",
        "staffing",
        "hrtech",
        "people ops",
        "talent acquisition",
        "learning and development",
        "employee engagement",
        "payroll",
        "benefits",
        "workforce management",
        "ecommerce",
        "retail",
        "retail media",
        "marketplaces",
        "direct to consumer",
        "consumer brands",
        "consumer apps",
        "creator economy",
        "social commerce",
        "logistics",
        "supply chain",
        "manufacturing",
        "industrials",
        "procurement software",
        "warehouse operations",
        "fleet management",
        "shipping",
        "last mile delivery",
        "construction",
        "real estate",
        "proptech",
        "smart buildings",
        "facility management",
        "hospitality",
        "travel",
        "aviation",
        "restaurants",
        "foodtech",
        "agritech",
        "energy",
        "oil and gas",
        "renewable energy",
        "solar",
        "battery tech",
        "climate",
        "climate tech",
        "cleantech",
        "utilities",
        "carbon markets",
        "mobility",
        "automotive",
        "electric vehicles",
        "autonomous vehicles",
        "telematics",
        "aerospace",
        "space",
        "defense",
        "govtech",
        "public sector",
        "civic tech",
        "edtech",
        "higher education",
        "k12 education",
        "legaltech",
        "compliance software",
        "regtech",
        "consulting",
        "professional services",
        "managed services",
        "outsourcing",
        "accounting",
        "telecom",
        "media",
        "advertising",
        "entertainment",
        "gaming",
        "streaming",
        "sports tech",
        "news media",
        "product management",
        "design",
        "operations",
        "knowledge management",
        "collaboration software",
        "future of work",
        "productivity software",
        "private equity",
        "venture capital",
        "family office",
        "investment banking",
        "startups",
        "founder tools",
        "robotics",
        "industrial automation",
        "semiconductors",
        "electronics",
        "iot",
        "digital twins",
        "search",
        "automation software",
        "workflow software",
        "document ai",
        "enterprise search",
        "call center software",
        "procuretech",
        "insurance",
        "real assets",
        "franchise",
        "franchise tech",
        "frictionless checkout",
        "identity verification",
        "fraud prevention",
        "governance risk and compliance",
    ]
)

TOPICS = _dedupe_terms(
    [
        "agents",
        "agent orchestration",
        "multi agent systems",
        "automation",
        "workflow",
        "enterprise",
        "b2b",
        "growth",
        "strategy",
        "operations",
        "execution",
        "scaling",
        "copilots",
        "genai",
        "llm",
        "rag",
        "evals",
        "fine tuning",
        "prompting",
        "tool use",
        "orchestration",
        "observability",
        "security",
        "application security",
        "cloud security",
        "data security",
        "identity security",
        "compliance",
        "governance",
        "risk management",
        "analytics",
        "data engineering",
        "data quality",
        "data governance",
        "data catalog",
        "etl",
        "elt",
        "vector database",
        "data warehouse",
        "lakehouse",
        "platform engineering",
        "developer experience",
        "devops",
        "mlops",
        "aiops",
        "reliability",
        "sre",
        "incident response",
        "postmortem",
        "on call",
        "cloud costs",
        "finops",
        "zero trust",
        "identity",
        "fraud",
        "abuse prevention",
        "product",
        "roadmap",
        "design",
        "user research",
        "onboarding",
        "activation",
        "retention",
        "churn",
        "personalization",
        "experimentation",
        "ab testing",
        "pricing",
        "packaging",
        "monetization",
        "upsell",
        "cross sell",
        "plg",
        "product led growth",
        "product marketing",
        "positioning",
        "messaging",
        "brand",
        "storytelling",
        "community",
        "distribution",
        "partnerships",
        "ecosystem",
        "channel sales",
        "alliances",
        "sales",
        "pipeline",
        "forecasting",
        "enablement",
        "outbound",
        "inbound",
        "lead gen",
        "demand gen",
        "account based marketing",
        "abm",
        "revops",
        "customer success",
        "customer support",
        "renewals",
        "expansion revenue",
        "procurement",
        "vendor management",
        "hiring",
        "recruiting",
        "talent",
        "management",
        "leadership",
        "founder mode",
        "case study",
        "benchmark",
        "playbook",
        "lessons",
        "templates",
        "mistakes",
        "launch",
        "demo",
        "gtm",
        "roi",
        "best practices",
        "implementation",
        "architecture",
        "stack",
        "migration",
        "integration",
        "api design",
        "sdk",
        "workflow automation",
        "process mining",
        "document processing",
        "knowledge base",
        "search",
        "enterprise search",
        "chatbots",
        "voice agents",
        "contact center",
        "support automation",
        "revenue cycle",
        "claims automation",
        "prior authorization",
        "clinical documentation",
        "sales ops",
        "marketing ops",
        "people ops",
        "finance ops",
        "legal ops",
        "supply chain ops",
        "procurement ops",
        "customer onboarding",
        "time to value",
        "expansion",
        "conversion",
        "click through rate",
        "attribution",
        "measurement",
        "dashboards",
        "budgeting",
        "planning",
        "scenario planning",
        "board reporting",
        "fundraising",
        "series a",
        "seed",
        "partnership strategy",
        "competitive intelligence",
        "battlecards",
        "customer stories",
        "thought leadership",
        "ops review",
        "qbr",
        "pipeline review",
        "security review",
        "architecture review",
        "design review",
        "retrospective",
        "career growth",
        "manager training",
        "change management",
        "digital transformation",
        "erp modernization",
        "crm hygiene",
        "cpq",
        "quote to cash",
        "order management",
        "inventory planning",
        "forecast accuracy",
        "warehouse automation",
        "routing",
        "capacity planning",
        "energy efficiency",
        "sustainability reporting",
        "carbon accounting",
        "model context protocol",
        "mcp",
        "browser automation",
        "computer use",
        "agent memory",
        "knowledge graphs",
        "graph rag",
        "synthetic evals",
        "grounded generation",
        "human in the loop",
        "approval workflows",
        "audit trails",
        "SOC 2",
        "HIPAA",
        "PCI",
        "GDPR",
        "KYC",
        "AML",
        "identity verification",
        "search relevance",
        "recommendation systems",
        "personal knowledge management",
    ]
)

QUERY_PROGRESS_INTERVAL = 10
CAMPAIGN_EXPANSION = "recursive"
QUERY_WAVE_SIZE = 100_000
WAVE_INDUSTRY_COUNT = 8
WAVE_INDEX = 0
JOB_PREFIX = f"million-corpus-searxng-ultrabroad-recursive-v4-wave{WAVE_INDEX + 1}"
SEARXNG_URL = os.environ.get("ULTRABROAD_SEARXNG_URL") or os.environ.get("SEARXNG_URL") or "http://127.0.0.1:8080"


def build_queries() -> list[str]:
    start_industry = max(0, int(WAVE_INDEX)) * max(1, int(WAVE_INDUSTRY_COUNT))
    end_industry = start_industry + max(1, int(WAVE_INDUSTRY_COUNT))
    wave_industries = INDUSTRIES[start_industry:end_industry] or INDUSTRIES[: max(1, int(WAVE_INDUSTRY_COUNT))]
    queries = content.build_harvest_queries(
        industries=wave_industries,
        topics=TOPICS,
        expansion=CAMPAIGN_EXPANSION,
    )
    queries = _filter_queries(queries)
    return queries[: max(1, int(QUERY_WAVE_SIZE))]


def emit_progress(event: dict[str, object]) -> None:
    event_type = str(event.get("event") or "")
    if event_type == "campaign_started":
        print(
            f"[content] campaign started: {event['job_count']} jobs across {event['query_count']} queries "
            f"limit={event['limit']}",
            flush=True,
        )
    elif event_type == "campaign_job_started":
        print(
            f"[content] campaign job {event['job_index']}/{event['job_count']}: "
            f"{event['job_id']} ({event['query_count']} queries)",
            flush=True,
        )
    elif event_type == "query_results" and int(event.get("result_count") or 0) > 0:
        print(f"[content] results: {event['result_count']} for {event['query']}", flush=True)
    elif event_type == "query_started":
        query_index = int(event.get("query_index") or 0)
        query_count = int(event.get("query_count") or 0)
        if query_index <= 3 or (QUERY_PROGRESS_INTERVAL > 0 and query_index % QUERY_PROGRESS_INTERVAL == 0):
            print(
                f"[content] query {query_index}/{query_count}: {event['query']}",
                flush=True,
            )
    elif event_type in {"query_failed", "query_backend_failed"} and event.get("query"):
        print(
            f"[content] {event_type}: {event['query']} :: {event.get('error')}",
            flush=True,
        )
    elif event_type == "campaign_job_completed":
        print(
            f"[content] campaign job complete: {event['job_id']} stored {event['stored_count']} "
            f"total {event['stored_total']}/{event['limit']}",
            flush=True,
        )
    elif event_type == "campaign_complete":
        print(f"[content] campaign complete: {event['stored_count']} stored across {event['job_count']} jobs", flush=True)


def main() -> None:
    queries = build_queries()
    print(
        f"[content] launching broad taxonomic campaign with {len(INDUSTRIES)} industries, "
        f"{len(TOPICS)} topics, {len(queries)} queries",
        flush=True,
    )
    summary = content.harvest_campaign(
        industry=INDUSTRIES[0],
        industries=INDUSTRIES,
        topics=TOPICS,
        query_terms=queries,
        limit=1_000_000,
        per_query=100,
        per_job_limit=2_000,
        queries_per_job=100,
        query_workers=2,
        job_prefix=JOB_PREFIX,
        progress=emit_progress,
        backend="public-only",
        public_search="searxng",
        searxng_url=SEARXNG_URL,
        resume=True,
    )
    print(summary, flush=True)


if __name__ == "__main__":
    main()
