# Generated by Django 6.0.6 on 2026-06-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_deal_email_routing"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="country_code",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
