# Generated by Django 6.0.6 on 2026-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(default="smtp.gmail.com", max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                ("username", models.CharField(max_length=320, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("from_address", models.EmailField(max_length=320)),
                ("daily_limit", models.PositiveIntegerField(default=30)),
            ],
            options={
                "verbose_name_plural": "Mailboxes",
            },
        ),
    ]
